[build]
    base = "Sample-01"
    command = """if [ -z "${AUTH0_DOMAIN}" ] || [ -z "${AUTH0_CLIENT_ID}" ] || [ -z "${AUTH0_AUDIENCE}" ]; then
            echo "Error: One or more environment variables (AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_AUDIENCE) are not set or are empty."
            exit 1
        fi
        printf '{\"domain\":\"%s\", \"clientId\":\"%s\", \"apiUri\":\"%s\", \"authorizationParams\":{\"audience\":\"%s\"}}' "${AUTH0_DOMAIN}" "${AUTH0_CLIENT_ID}" "${URL}" "${AUTH0_AUDIENCE}"> auth_config.json
        npm install
        npm run build
    """
    publish = "dist/login-demo"
